### users Index
GET http://localhost:3000/users.json

### users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
"email": "joyceroop+13@gmail.com",
"password": "password",
"password_confirmation": "password"
}

### users Show
GET http://localhost:3000/users.json


### users Destroy
DELETE http://localhost:3000/users/3.json


################################################


### pin_drop Index
GET http://localhost:3000/pin_drops.json

### pin_drop Show
GET http://localhost:3000/pin_drops.json

### pin_drop Create
POST http://localhost:3000/pin_drops.json
Content-Type: application/json

{
  "name": "technical zone",
  "user_id": 1
}

### pin_drop Delete
DELETE http://localhost:3000/pin_drops/1.json


################################################


### location Index
GET http://localhost:3000/location.json


### location Show
GET http://localhost:3000/location.json

### location Create
POST http://localhost:3000/location.json
Content-Type: application/json

{
  "latitude": 39.918147,
  "longitude": -105.25976,
  "pin_drop_id": 1,
  "description": "technical zone"
}

### location Delete
DELETE http://localhost:3000/location/3.json


################################################


### pin_drop_reaction Index
GET http://localhost:3000/pin_drop_reaction.json

### pin_drop_reaction Show
GET http://localhost:3000/pin_drop_reaction.json

### pin_drop_reaction Create
POST http://localhost:3000/pin_drop_reaction.json
Content-Type: application/json

{
  "name": "still there!",
  "image_url": "still there.png",
  "pin_drop_id": 2
}

### pin_drop_reaction Delete
DELETE http://localhost:3000/pin_drop_reaction/1.json



### sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "joyceroop@gmail.com",
  "password": "adidas77"
}